[package]
name = "vtm-export"
version.workspace = true
authors.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
voxelis.workspace = true

[features]
default = ["voxelis/vtm"]
