[package]
name = "voxelis-math"
version.workspace = true
authors.workspace = true
license.workspace = true
edition = "2024"

[dependencies]
glam.workspace = true
tracy-client = { workspace = true, optional = true }

[features]
default = []
tracy = ["dep:tracy-client"]
